version: 0.0
os: linux
files:
  - source:  /
#    destination: /home/ubuntu/github_actions
    destination: /home/ec2-user/BE-PopcornPicks-
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
