server:
  port: 3000

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/popcorn;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

kobis:
  key: 2655b1a898fb492614c88aae0b46666a
  api:
    url: http://kobis.or.kr/kobisopenapi
kmdb:
  url: https://api.koreafilm.or.kr/openapi-data2/wisenut/search_api/search_json3.jsp
  collection: kmdb_new2
  serviceKey: 8VWF4U07N5R1DB11Q12V
youtube:
  url: https://www.googleapis.com
  key: AIzaSyD6QU8KkpVy2-gDJVc2H3JOciGL8LsWDPk
  part: snippet
  type: video
